### PR TITLE
habit-tracker

### PR DESCRIPTION
**Pull request by roshannme**
habit tracker with pixela api without leaving cli

### CODE REVIEW

**Comment by thenishantsapkota** [comment]
@roshannme I just merged this Pull Request
Why is there a duplicate?

**Comment by roshannme** [comment]
what do you mean by duplicate?

**Comment by thenishantsapkota** [comment]
I already merged this PR a while ago, so this seems like a duplicate pull request.

**Comment by roshannme** [comment]
sorry it was accepted earlier thanks :)

**Pull request closed without merging**
