### PR TITLE
Adding new simple_login_system using C programming

### PR DESCRIPTION
**Pull request by aayushdhakal69**
Hello There! 
I added the simple login system which is able to do both sign up and login using file handling in C.

### CODE REVIEW

**Comment by thenishantsapkota** [comment]
Great job with the Login and Signup system.
Thank you for your contribution!

**Comment by aayushdhakal69** [comment]
> Great job with the Login and Signup system. Thank you for your contribution!

Hello sir! Why my request is not labeled as "hacktoberfest accepted" ?

**Comment by aayushdhakal69** [comment]
> Great job with the Login and Signup system. Thank you for your contribution!
Hello sir! Why there is no "hactoberfest-accepted" label in this PR?

**Comment by aayushdhakal69** [comment]
Hello sir! Can I know why there is no "hacktoberfest-accepted" level in this PR?

**Pull request merged**
